name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm install
      - run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to gh-pages
        run: npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
